title:            Cracking. Barnstorming. Brilliant
description:      
url:              http://leaguefls.github.io.
signoff:          denniskig
disqus_shortname: leagueflswordpresscom
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-47829370-1

links:
  - name:         BLOG
    url:          /
  - name:         ABOUT
    url:          /about

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
